export enum NotificationType {
  NEW_LEAD = 'NEW_LEAD',
  MESSAGE_RECEIVED = 'MESSAGE_RECEIVED',
  FOLLOWUP_ONE_HOUR = 'FOLLOWUP_ONE_HOUR',
  DAILY_FOLLOWUP_SUMMARY = 'DAILY_FOLLOWUP_SUMMARY',
  CONVERSATION_EXPIRING_1H = 'CONVERSATION_EXPIRING_1H',
  CONVERSATION_EXPIRED = 'CONVERSATION_EXPIRED',
  INSTALLMENT_DUE_TOMORROW = 'INSTALLMENT_DUE_TOMORROW',
  INSTALLMENT_OVERDUE = 'INSTALLMENT_OVERDUE'
}
